<a href="https://colab.research.google.com/github/Kreetika-rana/Assignment1/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

array=np.array([10,20,30,40,50])
print(array)

[10 20 30 40 50]


In [2]:
addition=array+2
print(addition)

[12 22 32 42 52]


In [4]:
multiply=array*3
print(multiply)

[ 30  60  90 120 150]


In [3]:
divide=array/2
print(divide)

[ 5. 10. 15. 20. 25.]


In [5]:
arr=np.array([1,2,3,6,4,5])
reversed_array=arr[::-1]
print(reversed_array)

[5 4 6 3 2 1]


In [6]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
a=np.bincount(y).argmax()
index=np.where(y==a)[0]
print("Most Occuring: ", a)
print("Index: ", index)

Most Occuring:  1
Index:  [0 1 2]


In [7]:
array2d=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
x1=array2d[0,1]
x2=array2d[2,0]
print(x1,x2)

20 70


In [8]:
YourName= np.linspace(10,100,25)
print(YourName)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [9]:
print(YourName.ndim)

1


In [10]:
print(YourName.shape)

(25,)


In [11]:
print(YourName.size)

25


In [12]:
print(YourName.dtype)

float64


In [13]:
print(YourName.nbytes)

200


In [14]:
transpose_array=YourName.reshape(5,5)
print(transpose_array)

[[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]


In [15]:
ucs420=np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print(ucs420)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]


In [16]:
mean=np.mean(ucs420)
median = np.median(ucs420)
max_val = np.max(ucs420)
min_val = np.min(ucs420)
unique_elements = np.unique(ucs420)

print("Mean:", mean)
print("Median:", median)
print("Max:", max_val)
print("Min:", min_val)
print("Unique elements:", unique_elements)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]


In [17]:
reshape=ucs420.reshape(4,3)
print(reshape)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [18]:
import numpy as np
ucs420 = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
resized_array = ucs420[:2, :3]
print(resized_array)

[[10 20 30]
 [50 60 70]]
